<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="layouts/css/style.css">
    <script src="https://kit.fontawesome.com/b1361fb5d5.js" crossorigin="anonymous"></script>

    <title>Home | Instinct Games</title>
</head>
<body>
    <?php include("includes/nav.php");
    ?>
    <div class="wrapper" style="background-color:#1b1b1b;">
        <div class="slider">
            <div class="slide-img" >
                <img src="layouts/img/2.jpg" alt=""  >
                <div class="buttonn left">
                <i class="fas fa-long-arrow-alt-left"></i>
                </div>
                <div class="buttonn right">
                <i class="fas fa-long-arrow-alt-right"></i>
                </div>
            </div>
        </div>
        <div class="heading mt-30">
            <h1 class="ta-c ">Online Games</h1>
            <p class="ta-c">An online game is a video game that is either partially or primarily played through the Internet or any other computer network available.Online games are ubiquitous on modern gaming platforms, including PCs, consoles and mobile devices, and span many genres, including first-person shooters, strategy games, and massively multiplayer online role-playing games (MMORPG).In 2019, revenue in the online games segment reached $16.9 billion, with $4.2 billion generated by China and $3.5 billion in the United States.Since 2010s, a common trend among online games has been operating them as games as a service, using monetization schemes such as loot boxes and battle passes as purchasable items atop freely-offered games.Unlike purchased retail games, online games have the problem of not being permanently playable, as they require special servers in order to function.</p>
        </div>
        <div class="games">
            <div class="game">
                <div class="game-heading mt-30">
                    <h3 class="ta-c">ARK:Survival Evolved</h3>
                </div>
                <div class="game-img">
                    <img src="layouts/img/2.jpg" alt="">
                </div>
                <div class="game-btn">
                    <input type="button" onclick="document.location='GamePage.php'"class="button1 edited" value="VIEW" style="box-shadow: 0 0 15px #30593D;">
                </div>
            </div>
            <div class="game">
                <div class="game-heading mt-30">
                    <h3 class="ta-c">Atlas</h3>
                </div>
                <div class="game-img">
                    <img src="layouts/img/4.jpg" alt="">
                </div>
                <div class="game-btn">
                    <input type="button" onclick="document.location='GamePage2.php'"class="button1 edited" value="VIEW" style="box-shadow: 0 0 15px #30593D;">
                </div>
            </div>
        </div>
        
    </div>

    <?php include("includes/footer.php");
    ?>
</body>
</html>